services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.9.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  fake-data-producer:
    build: ./fake-data-producer
    depends_on:
      - kafka

  exchange-data-consumer:
    build:
      context: ./ExchangeDataConsumer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    restart: always

  # ai-assistent:
  #   image: ai/deepseek-r1-distill-llama:8B-Q4_0
  #   ports:
  #     - "8087:8087"

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,dynamodb
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - LOCALSTACK_TMPDIR=/var/tmp/localstack-tmp
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - localstack_data:/var/lib/localstack

  deployer:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    depends_on:
      - localstack
    volumes:
      - ./USDHandlerFunction:/app/lambda
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    command: ["/app/deploy.sh"]

volumes:
  localstack_data: